language: python
dist: trusty
cache: pip
python:
  - "2.7"
#  - "3.4"
# command to install dependencies
install:
  - pip install -e .
  - pip install coveralls
# command to run tests
script:
  - coverage run setup.py test
  - coverage combine
after_success:
  - coveralls
