language: python
python:
  - "2.7"
#  - "3.4"
# command to install dependencies
install:
  - pip install -e .
  - pip install coveralls
# command to run tests
script:
  coverage run --source=AegeanTools setup.py test
after_success:
  coveralls
