language: python
dist: trusty
cache: pip
python:
  - "2.7.14"
  - "3.7.4"
# command to install dependencies
install:
  - pip install .
  - pip install coveralls
  - pip install codacy-coverage
# command to run tests
script:
  - coverage run setup.py test
  - coverage combine
after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
